### ISSUE TITLE
Characters in the description of the Process 

### ISSUE THREAD

**Issue by jmoralesdalmau** [ospin-web-dev/non-repo-issues#101]
All information you provide is helpful to us! Thank you for taking the time.

### Describe the feature / change request
I would like we are able to introduce at least 500 characters into the description of the process, not 250.

![image](https://user-images.githubusercontent.com/58782447/139062302-77a718e4-b38d-4fdd-a67f-a405688112e7.png)

**Comment by vdiezel** [comment]
That is easy to do!

**Comment by vdiezel** [comment]
Added to the next sprint

**Comment by vdiezel** [comment]
this was merged
