### ISSUE TITLE
Confirmation button after creating a phase

### ISSUE THREAD

**Issue by jmoralesdalmau** [ospin-web-dev/non-repo-issues#104]
All information you provide is helpful to us! Thank you for taking the time.

### Describe the feature / change request
Do we need a "Confirmation" button after creating the phase?

![image](https://user-images.githubusercontent.com/58782447/139412866-637f12de-73c7-46ed-bf19-91b1047438a4.png)

Just to be sure all is well setup. I would like to brainstorm.

**Comment by vdiezel** [comment]
Because it is easy to get rid of a phase, and for running processes where it might be crucial we have the changes table that need to be confirmed before we add changes, I'll dismiss this request.
