### ISSUE TITLE
Remove more than process at a time

### ISSUE THREAD

**Issue by jmoralesdalmau** [ospin-web-dev/non-repo-issues#106]
### Description

I would like to have the possibility to select, for instance from a clickable box, the process I would like to remove, and then remove them at once. 

### Reasoning

I want to eliminate almost all processes from the image. As I have to do it now, it will take me a while, because I have to do it one by one. If I could select which ones, and then eliminate them at the same time, this would save me a lot of time (also because I have hundreds of these processes).

This goes very close to another ticket related to be able to drag into folders to differentiate between them.

### Screenshots or additional info

```markdown
![image](https://user-images.githubusercontent.com/58782447/140477665-66a726cc-9510-4129-9da4-308ee73502aa.png)
```

**Comment by vdiezel** [comment]
This is possible in the table view.
