### ISSUE TITLE
Graph doesn't show process data but is running

### ISSUE THREAD

**Issue by felixloeser** [ospin-web-dev/non-repo-issues#108]
### Description

No data shown in the graph for pump speed on pump serial 2, direction is shown properly, device worked

### How severe is the impact for you

major

### Has this been encountered internally or by a customer

external

### URL link to the view with the problem

https://ospin-app.com/device/9e3ca042-35c7-4581-8923-4e3905370982/process/a9d88ce0-8333-447d-a369-65b14de1996b?active-tab=dataviewer

### Steps To Reproduce

in cloned process same behaviour

### Screenshots or additional info

```markdown
Screenshot 2021-11-18 at 15.41.12
```

### In wich environments did you encounter the bug?

Production

**Comment by vdiezel** [comment]
devices where sending values of null
