### ISSUE TITLE
Heidolph Device didn't perform any action even with targets set properly

### ISSUE THREAD

**Issue by felixloeser** [ospin-web-dev/non-repo-issues#110]
### Description

We programmed a process and started it remotely but the overhead stirrer didn't work at all, at any of the phases

### How severe is the impact for you

major

### Has this been encountered internally or by a customer

internal, external

### URL link to the view with the problem

https://ospin-app.com/device/01d8eb46-04fe-4369-a165-24eab5411dca/process/48671f2e-c089-44c7-a268-aa0f365671c2?active-tab=dataviewer

### Steps To Reproduce

https://ospin-app.com/device/01d8eb46-04fe-4369-a165-24eab5411dca/process/48671f2e-c089-44c7-a268-aa0f365671c2?active-tab=dataviewer

cloned process had same behaviour

### In wich environments did you encounter the bug?

Production

**Comment by vdiezel** [comment]
Not a webapp bug.
