### ISSUE TITLE
Deleting of shared process - unclear warning

### ISSUE THREAD

**Issue by felixloeser** [ospin-web-dev/non-repo-issues#113]
### Description

When an operator tries to deletes a process that is shared with him (which they shouldn't be able to do), they receive the same warning as an admin (who can delete that process) and no change. Process is still available

Expectation: 
- operator tries to delete process they are not the owner of
- warning: you cannot delete this process, you don't have the right to. Do you want to hide it?
- Depending on the selection, process still remains visible or is hidden

### How severe is the impact for you

minor

### Has this been encountered internally or by a customer

internal

### Steps To Reproduce

- Share a process with an operator account at operator level access for the process
- try to delete the the process from the operator account
- deletion warning should appear
- when selecting delete, process state is unchanged

**Comment by FelixMZ2018** [comment]
this has been adressed, there is now a message informing an operator that they are not allowed to delete a process
