### ISSUE TITLE
as an employee at Ospin I have access to important device data stored remotely

### ISSUE THREAD

**Issue by vdiezel** [ospin-web-dev/non-repo-issues#21]
As much data as possible about a device should be stored remotely, including

1. Flashed firmware commits
2. serial numbers of integrated hardware, pumps, sensors etc..
3. Integrated modules
4. Device logs
...

**Comment by DanielSeehausen** [comment]
closing as some of this is now duplicated into specific logging tickets for upcoming work. 
will extend what we have and break out more specific tickets once we have feature requests/specs
