### ISSUE TITLE
add to confluence documentation the expected events payload/urls

### ISSUE THREAD

**Issue by DanielSeehausen** [ospin-web-dev/non-repo-issues#39]
currently, the metal meats cloud is the source of truth of these payloads

**Comment by vdiezel** [comment]
![Bildschirmfoto von 2020-03-19 17-09-18](https://user-images.githubusercontent.com/37934155/77089039-97a86e00-6a05-11ea-8d38-00c6f3a1edc6.png)
![Bildschirmfoto von 2020-03-19 17-09-42](https://user-images.githubusercontent.com/37934155/77089048-9a0ac800-6a05-11ea-813e-c72699b7d112.png)
