### ISSUE TITLE
reload of the page after start/pause/resume

### ISSUE THREAD

**Issue by Se1en** [ospin-web-dev/non-repo-issues#78]
All information you provide is helpful to us! Thank you for taking the time.

### Describe the feature / change request
could you add a refresh/reload of the screen/process/webpage automatically after any start/stop/pause/resume? 
after pause/resume/... buttons the screen/webpage does not always load live stuff. it often shows settings of builder page or says 'no data' on data viewer page after launch of a process. it seems like this issue with not loading the live processes occurs only when the pause it bit longer (minutes), not only seconds. 

https://staging.ospin-app.com/device/6146a711-accf-422a-a70d-910ada0d765e/process/c0f942a8-a216-4d3d-bf53-3b938700ef5a

### Screenshots
it works perfectly here, where the pause and resume was just seconds apart:
![image](https://user-images.githubusercontent.com/73227192/98094726-f1bd4d00-1e89-11eb-801c-35a94dc2e11f.png)
![image](https://user-images.githubusercontent.com/73227192/98094867-24ffdc00-1e8a-11eb-85a9-268d62cc1e1a.png)
![image](https://user-images.githubusercontent.com/73227192/98094920-32b56180-1e8a-11eb-9e63-50aef10dad43.png)

but once the pause is for more than few seconds like here for almost 8 minutes
![image](https://user-images.githubusercontent.com/73227192/98099943-7b701900-1e90-11eb-8cc7-6acdc345d0fd.png)
even after resuming the process, it does not show live stuff and the buttons for resume/stop are still there and i have to reload the page manually to check, if i have running data, even when i hear the machine is back on and buzzing. im afraid i have not pictures as a proof, but please believe me :D

### Additional context
just user friendly stuff... 
thanks!

**Comment by vdiezel** [comment]
This is probably caused by AWS IoT sockets disconnecting after a while, as described here: 

https://github.com/ospin-web-dev/REACTor/issues/363

I will update the ticket and give it a higher priority
