### ISSUE TITLE
Calibration issue in Charité 2 bioreactor

### ISSUE THREAD

**Issue by aahmed2021** [ospin-web-dev/non-repo-issues#82]
All information you provide is helpful to us! Thank you for taking the time.

### To Reproduce
1. Go to 'Chrité2 device'
2. Click on 'tempsensors calibration- process'
3. try to calibrate any sensor
4. click on the calibrate button
5. in the calibration windows i can see only the first 12 minutes  and it is no possible to see the last date or the live data.

https://staging.ospin-app.com/device/7e9a59fd-d582-40f1-b22a-b947565eb166/process/64f45ab0-31b4-4093-a42c-84e69396a5b2

### Expected behavior
I expect the live data or all of the data to be displayed so that I can select a time interval and calibrate there.

### Screenshots
![image](https://user-images.githubusercontent.com/56728314/99258830-6c3a8500-2819-11eb-8eaf-b577dc2b5e7c.png)

### Environment
 - [ ] Development (https://dev.ospin-app.com)
 - [x ] Staging (https://staging.ospin-app.com)
 - [ ] Production (https://ospin-app.com)
 - [ ] Demo (https://demo.ospin-app.com)

> Note: staging and production use the same database

**Comment by vdiezel** [comment]
not a bug - the wrong phase was chosen as the calibration modal always shows the data of the phase selected in the sidebar.
