### ISSUE TITLE
Detailed process information

### ISSUE THREAD

**Issue by O-Susanoo** [ospin-web-dev/non-repo-issues#84]
### Describe the feature / change request
I think it's very important for us to have a system where we know who did what , for example suppose a user created a process and another one stopped that process we can't knew who was responsible , same goes for example for phases if someone added a phase to the process , or even moved to the next phase we have no way of understanding who made such an action, i think a system that details every interaction with the process is very important

**Comment by DanielSeehausen** [comment]
closing as this feature exists within device/process logs
if specific actions need to be logged that aren't - please open a new ticket mentioning which actions are not logged!
