### ISSUE TITLE
Adjust the data-order of all sensors in Charité 1 and 2

### ISSUE THREAD

**Issue by aahmed2021** [ospin-web-dev/non-repo-issues#86]
All information you provide is helpful to us! Thank you for taking the time.

### Describe the feature / change request

As you know the charité hast two smiliar bioreactors. If they run a process they downlod the whole data of all sensors and they want to read autmatically. The problem is the columns in both bioreactors not the same. e.g. If you compare which date is in the second column: in the first bioreactor,you will have the medium in speed. in the second bioreactor tyou will have the ph sensor.

That caused a lot of manually work and time. Do you see any possiblity to put all date in right order?

### Screenshots
![image](https://user-images.githubusercontent.com/56728314/118802344-4d897980-b8a2-11eb-8df3-236e3fe766aa.png)
![image](https://user-images.githubusercontent.com/56728314/118802396-5bd79580-b8a2-11eb-822f-b2a5ed8988f7.png)

### Additional context
Add any other context about the feature/change request here

**Comment by FelixMZ2018** [comment]
@aahmed2021 

Hey! 

I've just deployed the fix for this so the streams should be consistent now, more information can be found in the changelog (https://ospin-app.com/changelog) 

Please let me know if there are any issues with it

Thanks!

**Comment by aahmed2021** [comment]
Thanks Felix,
It was very quick :)
