### ISSUE TITLE
External Bug Report

### ISSUE THREAD

**Issue by TurgutOspin** [ospin-web-dev/non-repo-issues#90]
### Describe the bug
Usually I see the **500 OOPSIN** page after starting a process with clone configuration ( [Test process link](https://ospin-app.com/device/9ef4f0b3-977b-4d36-9760-bba0b789bb0c/process/e2f48b54-b74c-4efa-919c-6c55b5f80e6a?active-tab=overview)).

After  the crash page, I can access to the device  and data, when I refresh the page, otherwise it is redirecting to the 500 OOPSIN  page.

As far as I see, after starting a process with 5second phases,  which is almost equal to data update interval, then web app is going to crash.

This 5s process phases are required for putting a load on communication channel .
 
 The purpose of this test was putting a load on communication channels to see the weak points of device.

### To Reproduce
**Environment:**
-ZIM CT2 bioreactor.
-Ospin web  app

**Steps to reproduce the behaviour:**
1. Clone a new process from link above.
2. Click to the start button
3. Immediately try to access to the Data view tab.
4. By the clicking to the  Data view tab, error used to appear.

### Expected behaviour
Redirecting to 500 OOPSIN page.

**Comment by vdiezel** [comment]
This has been fixed.
