### ISSUE TITLE
PID 500

### ISSUE THREAD

**Issue by WM-OSPIN** [ospin-web-dev/non-repo-issues#94]
All information you provide is helpful to us! Thank you for taking the time.

### Describe the bug
I am not able to read PID values from process:
https://ospin-app.com/device/d880ab76-c59b-45be-af2d-1522103e501d/process/0d6f12a9-fea0-4ab8-bf53-24244447d760?active-tab=builder

I have error 500:

TypeError: Cannot read property 'slots' of undefined
Error in
 FileName: components/processviewer/body/builder/ControllerStream.jsx
 Function: Process.isExecutable at line: 54
 
 I was on Production enviroment using OSPIN Support account.

### To Reproduce
_(providing the URL this can be reproduced on (when applicable) is very helpful as it contains specific information for us! Feel free to copy and paste it directly)_

### Screenshots
(an easy way to do this is to make sure an image is copied to clipboard, then you can just `ctrl + v` right in line here and GitHub will do the rest. click and drag also works.)

### Environment
 - [ ] Development (https://dev.ospin-app.com)
 - [ ] Staging (https://staging.ospin-app.com)
 - [ ] Production (https://ospin-app.com)
 - [ ] Demo (https://demo.ospin-app.com)

> Note: staging and production use the same database

**Comment by vdiezel** [comment]
fixed here: https://github.com/ospin-web-dev/REACTor/pull/1392
