### ISSUE TITLE
User Sign-up: Unhelpful Error Message when blank space in user name

### ISSUE THREAD

**Issue by felixloeser** [ospin-web-dev/non-repo-issues#96]
A Heidolph employee wanted to sign up to the webapp but in the user sign-up entered the name with a blank space. A not helpful message was displayed.

Either a tool-tip or the error message should display what was actually wrong with the input.

![Anmeldung Joachim](https://user-images.githubusercontent.com/64835544/130644317-1d92437d-b8f0-4156-93ae-0bb36e91550c.PNG)

**Comment by vdiezel** [comment]
This is bad and will be addressed!

**Comment by vdiezel** [comment]
Transferred to ticket - white spaces will be blocked.
