### ISSUE TITLE
External Bug Report

### ISSUE THREAD

**Issue by ccompadre** [ospin-web-dev/non-repo-issues#97]
All information you provide is helpful to us! Thank you for taking the time.

### Describe the bug
Two lines showing for ramp up and down changing motor speed

### To Reproduce
1. Start a Process with pumps
4. See error /https://ospin-app.com/device/cd9f5b6e-49c7-474b-8e11-b683d8857891/process/28c0ae66-fcf8-4100-8996-1c3a2f6346cd?active-tab=dataviewer

### Expected behavior
one line ramping up or down to speed

### Screenshots

![Chart](https://user-images.githubusercontent.com/74594308/134200712-79d80f75-0ad2-4b2f-b3ce-ac1f05a3959b.jpeg)
### Environment
 - [ ] Development (https://dev.ospin-app.com)
 - [ ] Staging (https://staging.ospin-app.com)
 - [x ] Production (https://ospin-app.com)
 - [ ] Demo (https://demo.ospin-app.com)

> Note: staging and production use the same database

**Comment by vdiezel** [comment]
This seemed a temporary problem. Closed.
